#!/usr/bin/env python

import sys, yaml, json

## Multiline strings represented in flow style
## Also tags unicode strings as plain yaml strings (good?)
def folded_multiline_representer(dumper, data):
    style = '>' if "\n" in data else None
    return dumper.represent_scalar(u'tag:yaml.org,2002:str', data, style=style)
yaml.add_representer(str, folded_multiline_representer)
yaml.add_representer(unicode, folded_multiline_representer)

yaml.dump(json.load(sys.stdin), sys.stdout,
    default_flow_style=False,
    explicit_start=True)
